source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'pg'
gem 'sass-rails', '~> 4.0.0'
gem 'sprockets', '2.11.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'haml-rails'
gem 'jquery-rails'
gem 'jquery-ui-rails', '< 5.0.0'
gem 'compass-rails', '~> 1.1.2' # you need this or you get an err
gem 'foundation-rails'
gem 'resque'
gem 'resque-scheduler'
gem 'simple_form'
gem 'cocoon'
gem 'paperclip'
gem 'ankaa-statistic', git: 'git@bitbucket.org:myxrome/ankaa-statistic.git'
gem 'ankaa-content', git: 'git@bitbucket.org:myxrome/ankaa-content.git'
gem 'devise'
gem 'nokogiri'
gem 'figaro'
gem 'unicorn'

